version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "monthly"
      time: "10:00"
      timezone: Europe/Berlin
    labels:
      - "dependencies"
      - "automerge"
    open-pull-requests-limit: 10